services:
  - type: web
    name: snaplink-backend
    runtime: node
    rootDir: snaplink-backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false        
      - key: BASE_URL
        value: https://snaplink-backend-d87c.onrender.com
      - key: FRONTEND_URL
        sync: false        
